var Pfuture = {
0:"The Fool<p>\
The Fool is the first card in the Major Arcana, and is given the number zero to indicate that it is the very beginning—before everything. Many people misinterpret the Fool, believing its message to signify absurdity or moronic behavior. On the contrary, the Fool is a symbol of the Creator, the “All That Is”, or however you envision deity. He symbolizes the trickster aspect of divinity: God’s sense of humor, if you will. The Fool seems to be stepping off a cliff to certain doom. He turns his face and eyes upward, not noticing the fate that awaits. In his satchel, he has what little he needs for his journey. His companion, a little white dog, runs along at his heels. The dog can be seen as humanity’s most extreme attitudes toward divinity: either seen as following blindly along, or lacking the firmness of belief necessary to take the step the Fool is about to make, and therefore, trying to hold him back.\
The Fool in your future indicates that there will come a time when you will need to look at your situation with optimism. You will be required to make a leap of faith, taking only the baggage that benefits you, with the ultimate trust that you will make it alright. The Fool will encourage you to go beyond your boundaries, to work past your fears, and to believe that anything is possible.\
",
1:"The Magician<p>\
The Magician is the second card of the Major Arcana, and is given the number one to indicate the power that resides within each living being: the power of the self. He has mastered the tools of the Tarot: the pentacle, cup, sword, and wand, which symbolize the four physical elements of earth, water, air, and fire. With one hand aiming skyward and one pointing at the ground, the Magician is the symbol of manifestation, of bringing things from the spiritual or psychological realm into the physical one. The power flowing through him is the power of creation, which is symbolized by the flowers and other growing things around him.\
The Magician in your future indicates a need for awareness: watch what you bring into your life as well as what you give to others. You have to walk your talk: decide what you want and take action to make your dreams a reality. You alone have the power within you—you need only to concentrate on channeling it to your best advantage.\
",
2:"The High Priestess<p>\
The High Priestess is the third card in the Major Arcana, and is given the number two to indicate the polarity inherent in all things. She sits between the pillars of light and darkness, mercy and severity, positive and negative. She has withdrawn from outside influences, going deep within to gain knowledge from behind the veil of consciousness. The scroll in her lap is labeled “TORA”, the name of the Hebrew holy book, indicating her link to divinity. Behind her, the eternal ocean of emotions and intuition ebbs and flows, and she is the key to its mysteries.\
The High Priestess in your future indicates that you will seek more esoteric knowledge, and experience a spiritual awakening. The attainment of such wisdom will require discipline. She also advises you to look for the subtle meanings beyond everyday events. You must listen to your inner voice to hear the truth that lies beyond the shallow, mundane world. Remember to trust your instincts.\
",
3:"The Empress<p>\
The Empress is the fourth card in the Major Arcana, and is given the number three to signify many forms of fertility, including the reproduction that comes from human partnership. She, like the planet Venus whose symbol adorns her, rules love. The gentleness and emotional sides of motherhood are her domain. Growth is embodied in the fields of grain beneath her feet. The grain sustains and supports human life. The Empress is, in this way, an expression of mother Earth. In some instances, she can indicate a pending marriage, or herald the arrival of motherhood.\
The Empress in your future indicates that you will use loving, caring ways to accomplish your goals without losing your power. You will be required to put your heart and soul into your undertakings, and cultivate your talents, but retain your control over the situation. Do not let yourself become either too easily swayed or too inflexible. Above all, you will be the best barometer of what is right for you. Remember to use your judgement\
",
4:"The Emperor<p>\
The Emperor is the fifth card in the Major Arcana, and is given the number four to indicate order and structure in the material sense, much like the four lines that create a square. He indicates an authority figure who is practical in his dealings. The rams on his throne are the symbols of Aries, the first sign of the Zodiac. Aries is ruled by Mars, the planet of war. His garments are red, the color most often associated with Mars, and symbolize passion, vitality, and aggressive actions. His sceptre, symbol of his power and dominance, is aimed upward, indicating aspiration and readiness. The mountains behind him denote solidity and immobility.\
The Emperor in your future indicates that you will rely on reason and logic to tackle the situation. To gain control, you must exhibit responsibility, maturity, and other leadership capabilities. This will be a good time to review your strategy, examine your options, consider your actions, and make sure they are in line with your personal code of ethics.\
",
5:"The Hierophant<p>\
The Hierophant is the sixth card in the Major Arcana, and is given the number five to indicate transformation and flux. He imparts his knowledge to those who are willing to listen, kneeling before him to receive the gift of his wisdom. He blesses them, with his upright hand forming the sign of benediction. His sceptre and crown denote his position of absolute authority. He symbolizes organized religions and the inner teacher, both guides along the path that leads to deity, hence the two crossed keys at his feet. Those who seek his guidance learn that they must also look within for answers.\
If your situation involves your career, the Hierophant in your future indicates that you will seek employment in a large corporation with strict requirements and expectations. The Hierophant symbolizes a knowledge of rules, regulations, customs, and the acceptable methods used in the situation—but does not restrict you to those traditional answers. You may have to go outside of the standards when it will be in your own best interest to do so.\
",
6:"The Lovers<p>\
The Lovers is the seventh card in the Major Arcana, and is given the number six to indicate balance. It signifies the three realms of the mind: the conscious, the subconscious, and the superconscious, embodied in the male, female, and the androgynous angelic figure above them. The man and woman are naked, symbolizing their honesty with each other as well as their physical accessibility. They represent that which is revealed. The winged figure above is clothed in robes, indicating the unknown, or that which is yet to be revealed...a mystery. Combined, these three elements form a complete whole.\
The Lovers symbolizes relationships, and harmonious interaction—both within the self and without. The Lovers card in your future indicates that love will be playing a crucial role in your life, and a decision will weigh heavily on your mind. The angel is thought to be Raphael, bringing healing to the situation. This symbolizes a need to mend fences, or heal yourself from a relationship that you will not be able to salvage. Look to your heart, and decide what it is you truly desire - what you will need to make yourself whole.\
",
7:"The Chariot<p>\
The Chariot is the eighth card in the Major Arcana, and is given the number 7, whose Qaballistic significance is victory. The number seven is also commonly associated with good luck. An armored man stands in an elaborate chariot, drawn by two sphinxes. One black, one white, they symbolize the positive and negative forces the charioteer has learned to balance and integrate. Above his head, a canopy of stars, indicating his travels beyond the mundane world. The crescent moons on his shoulders—one smiling, one frowning—denote that he has done the same with the gamut of his emotions. His armor shows that he is ready for physical challenges and his sceptre symbolizes his status and control.\
The Chariot in your future indicates that you will celebrate victory over the extremes in your life through balance, self-control, and the enforcement of your True Will. It can indicate success in the battle against old patterns and vices. By grounding and centering yourself, you will get a handle on your situation. Remember to mentally take the reins. Utilizing the power of your mind, you will successfully chart the course to your goals.\
",
8:"Strength<p>\
Strength is the ninth card in the Major Arcana, and is given the number eight, which is a number of great good fortune in Eastern traditions. This card is often associated with the Zodiac sign Leo, which is ruled by the Sun, and eight is the number of solar festivals celebrated by many Earth-centered religions. A gentle looking woman, robed in white for purity, cradles a fierce lion’s head in her tender hands. She appears to be soothing the beast, closing its japing jaws. The red lion symbolizes anger, rage, and violence. The symbol over the woman’s head is the sign of infinity, reminiscent of a halo, and denotes her spirituality and her enlightened mind. You may imagine the two figures on the card as the two sides of yourself: the woman is your superego, and the lion is your id.\
The Strength card in your future indicates that you will get control over your anger through an understanding of where it comes from. You may need to change your approach to difficulties and issues with others as well. By seeking first to understand and accept the more negative aspects of yourself and others, your situation will be managed more effectively, and with more beneficial results for everyone involved.\
",
9:"The Hermit<p>\
The Hermit is the Tenth card in the Major Arcana, and is given the number nine to indicate the pinnacle of enlightenment. He stands atop a cold, snowy mountain peak, at the end of a journey he has made alone. He holds a lantern and gazes down the way he has traveled, leading any other seekers to what he has attained. The lantern is rich in symbolism; it denotes both his enlightenment and his willingness to aid others to it. It contains a six-pointed star, which is comprised of two triangles pointing in opposite directions: one up, one down. This shape reveals more of the Hermit’s message: the journey has been inner as well as outer, and his seeking has been within as well as without. He leans on his staff, which is a symbol of his power, making practical use of what he has come to know and master. His grey cloak indicates that he has synthesized the light and dark aspects of himself for his own benefit.\
The Hermit in your future indicates that you will seek guidance. This may be your own “Higher Self” speaking to you, or it may be advice given to you by a trusted friend, or a seasoned professional. It is wise to listen to the wisdom that will be offered, and to your own gut feelings, in the situation. Those who speak from experience will be able to give you some much-needed perspective, as they have been down the path you will be following. The Hermit can also indicate a need to withdraw from the outer world to focus on your innermost self.\
",
10:"The Wheel of Fortune<p>\
The Wheel of Fortune is the eleventh card in the Major Arcana, and is given the number ten, which corresponds to the number of sephiroth in the Tree of Life. The Wheel spins in the midway point of the Major Arcana, indicating a crucial turning point. It is a metaphor for Karma, Fate, and Destiny. The creatures pictured in the corners of the card symbolize the elements of Earth, Air, Fire, and Water, just as the Pentacles, Swords, Wands, and Cups of the Tarot do. The letters on the great Wheel can be arranged to form many different words that each have meaning: ROTA, the Latin word meaning wheel; ORAT, the Latin word meaning speaks; TARO, the phonetic pronunciation of Tarot, TORA, the Hebrew holy book and the word seen on the scroll of the High Priestess; and ATOR, thought to be another name for Hathor, an Egyptian Goddess. The snake on the Wheel has long been associated with evil, but is also an important symbol of transformation. The jackal-headed man is a representation of Anubis, an Egyptian God who is the guardian of the Underworld. The sphinx is attributed to Horus, associated with resurrection. In these three figures, the Wheel’s course of life, death, and rebirth is embodied. Only when you step back from the daily events in your life can you see the greater patterns—the Wheel itself in motion.\
The Wheel of Fortune in your future indicates that you will see situations in your life that come to a close, as well as new opportunities that will come to replace them. Major life decisions and milestones will be arriving, and some will have just passed. Things you set in motion some time ago will begin to bear fruit. Seeds you plant at this time will be sprouting when the Wheel comes full circle again. When you step back and examine the cause and effect of your situation, you will be able to adjust your actions accordingly to produce a better outcome.\
",
11:"Justice<p>\
Justice is the twelfth card in the Major Arcana, and is given the number eleven, which is considered a “master” number in numerology. Though the most familiar image of justice is that of a blindfolded woman, this image stares directly at us, unhindered...much more intimidating! Marking the halfway point in the Major Arcana, she symbolizes an equality between the past and the future—and the importance of the present to them both. She holds a set of balanced scales, and a sword, upright, ready for action. With her scales, she weighs all sides evenly, and with her sword, she cuts through the many layers of illusion and lies to the deeper truth. Her crown is a symbol of her status, gained through fair dealings, and her red robes indicate her power, passion, and vitality. With one foot visible, she is poised, ready to spring forth at any time to defend and act on the judgements she decrees.\
Justice in your future indicates that you will examine your past, and how the actions of your past have brought you to your present. In doing this, you will realize how what you do right now will influence who you become in the future. You will need to accept that your situation is one you helped create. In doing so, you will cut through the illusion of events to the wisdom you should be gaining from them. You can then begin to consciously take action to manifest better situations in your distant future. The Justice card often appears to signal that people will get what they deserve. If the situation in question has legal ramifications, it can indicate a fair trial, a settlement, or winning in any general legal battle...the honest side will triumph.\
",
12:"The Hanged Man<p>\
The Hanged Man is the thirteenth card in the Major Arcana, and is given the number 12 to indicate the combination of the Magician’s (1) mastery over the elements with the High Priestess’ (2) intuition and devotion to the search for esoteric knowledge. A man hangs by his ankle from a T shaped tree. The calm expression on his face and the fact that his hands are hidden behind his back indicate that he is not struggling; he has chosen to do this to gain enlightenment, symbolized by the halo around his head. Many religions contain tales of sacrifice leading to the betterment of humankind. The Hanged Man, like Odin or Christ, willingly gives up his mundane existence to attain a greater understanding that will benefit not only himself, but also his people.\
The Hanged Man in your future indicates that your situation will best be improved by letting go. This may involve a sacrifice of something you love in favor of your best interest, or it may mean that your struggle to manipulate and control things may make your situation worse. The action you should take in this case is to choose to be passive. If you relax and let events unfold, rather than second-guessing others and their motivations, you will discover the true meaning behind the scenario. The Hanged Man can indicate that you should do the opposite of what you would typically do, or what would be expected of you.\
",
13:"Death<p>\
Death is the fourteenth card in the Major Arcana, and is given the number 13 for many reasons...both the Death card and the number 13 are widely misunderstood. Most people regard both of them with fear, when in fact they are not cursed or unlucky at all—it is all a matter of your perspective. (That goes for physical death as well, actually.) An armored, skeletal figure rides a pure white horse, symbolic of spirituality and purity of body and soul. Death passes people from all walks of life, and each is effected in different ways that correspond to their viewpoint. The King, who believed that his existence hinged primarily on his status, title, and wealth, is laid low. The Priest, full of faith in a pleasant, rewarding afterlife, faces Death straight on. The young woman turns away out of fear and sadness, but kneels compliantly, albeit regretfully. The child, completely innocent and blissfully ignorant, offers Death the beauty of freshly picked flowers. The flowers, though beautiful, are now also dead. Interestingly enough, a flower appears on the flag Death carries. We should view Death, which essentially symbolizes change, the way the child does. In this way, Death becomes less traumatic, and more the transformation that it truly is meant to be. It is a positive passage, as the sun shining in the distance indicates.\
Death in your future indicates intense change, and most people do not welcome change. In its most positive guise, Death heralds a chance to start over, a second chance in relationships, or a time of major growth. If viewed with a negative outlook, Death can indicate the unexpected, and deep rooted fears of the unknown. If you accept change as it comes and grow from it, you can release that which has gone before and get on with what is yet to come. Discoveries, opportunities, and new cycles await you. Rather than resisting out of habit, remember to embrace them, and your worries will fade away.\
",
14:"Temperance<p>\
Temperance is the fifteenth card in the Major Arcana, and is given the number 14 to indicate that the Magician (1) has now learned to combine each of the four physical elements (4), to achieve balance. An angelic figure stands with one foot on land and one on the water, pouring liquid at an impossible angle from one cup to another with ease. This entity has integrated the emotional, spiritual, subconscious realm symbolized by the water with the physical, practical, conscious realm symbolized by the earth. The balancing act with the cups and the liquid denotes the ability to juggle situations fluidly, making it look effortless...though others may wonder how it is done! The bright sun in the distance and the planetary sigil for the Sun on the angel’s brow indicate a positive, promising outlook.\
Temperance in your future indicates that there will be a need for moderation in your situation. To bring things back into balance, you will be required to seek common ground with those involved, and rather than react defensively, act calmly. Speak your truth evenly, without too much anger (fire), without being too wishy-washy (water). Rather than taking off in an uncharted direction that will take you far off course, follow the road through the center. It will give you plenty of choices to bear left or right when necessary, but keep you close to the safety of the well-worn path. Temperance can be a warning to slow down, or simply to stop. This may include indulgences, vices, and bad habits. Remember to rethink and re-evaluate your position, and to ground and center yourself.\
",
15:"The Devil<p>\
The Devil is the sixteenth card in the Major Arcana, and is given the number 15 to indicate the Magician (1) using the (5) elements (earth, air, fire, water, and spirit) for materialistic purposes. Note the Devil’s four fingers and thumb held up (5), while the cudgel (1) aims the power down at the earth...the reverse position of the Magician. The inverted pentagram on the Devil’s forehead is a symbol indicating spirit submerged in and subjugated by matter, or the material world. The Devil presides over a couple from a superior position, in a perversion of the trio on the Lovers card. The couple remain chained to his solid block of stone, though the shackles are loose. They are naked, vulnerable—and yet their faces remain calm. They are entranced by the promises of superficial gain that the belief in the Devil has given them. They remain chained to their worldly desires, believing that only what is concrete and physical is important.\
When the Devil appears in your future, it can indicate pettiness, materialism, and base desires. In the Christian faiths, the Devil is the enemy. Like Lucifer, whose vanity and conceit cost him God’s favor, the Devil in the Tarot can be a warning to the selfish and egotistical. Overall, the Devil indicates that you will need to take a long, hard look at your darker self, and a reminder that if pushed to the side and allowed to fester in darkness, your dark side will only grow more grotesque, and erupt when you least expect it, or when you just plain lose control. If you fear that you have not fully accepted the parts of yourself you dislike, don’t lock them away. Bring them, slowly and safely, into the light. It will break the chains, and set you free.\
",
16:"The Tower<p>\
The Tower is the seventeenth card in the Major Arcana, and is given the number 16 to indicate the conscious mind represented by the Magician (1) faced with the breakdown of the unity found in the Lovers (6). Atop a craggy peak, the once-crowned Tower begins to crumble. Fire and Lightning ravage it from within and without. Two people, calling to mind the man and woman in the Lovers card (but clothed, indicating concealment), plunge to an uncertain fate, as flames erupt from the explosion. The destruction is devastating, but there is a purpose behind it. The walls of the Tower have been constructed by the materialistic Ego, and the force of chaos has come to tear them down in the name of spiritual development. The small, tear-shaped flames are symbolic because they resemble YOD, the first letter in the Hebrew name for God. They represent the spark of enlightenment that will brighten even the darkest hour.\
When The Tower appears in your future, it can indicate a time of turmoil. The phenomenon that “bad things” happen in threes, or other multiples, is a reality, and you may soon feel the rug of life being pulled out from under your feet. Like the Tower, you will feel you have been struck from out of nowhere. Remember that sometimes, a fire is needed to clear out dead wood, and clear space for the fresh seedlings that will someday be a great forest. If you feel overwhelmed, remember that you can only become stronger by surviving these trials.\
",
17:"The Star<p>\
The Star is the eighteenth card in the Major Arcana, and is given the number 17 to indicate the conscious mind represented by the Magician (1) opening up to the many directions possible with the control over his Chariot (7). Below one giant yellow star (1), and seven smaller white stars (7), a beautiful woman kneels with one knee on land and one foot on the water. With a jug in each hand, she pours water into both. She is taking inspiration from her creative, intuitive side (water), applying it to her surroundings and daily life (earth), and using the power it gives her to replenish the source of her creativity (water), making a complete cycle. In essence, she is healing herself with water, the source of all life. Her nakedness is symbolic of her purity and honesty, to others as well as to herself. She is in her most natural state, indicating that her task comes with ease, and her calm, serene expression gives her work a meditative quality.\
The Star in your future represents your hopes and dreams. If you have ever wished that you could do meaningful work that you could actually enjoy, the Star indicates an opportunity on the horizon. It will be time for you to pursue your dream. Strive to go to the source within your mind and heart, and replenish yourself by freeing your spirit, allowing your true self to shine through. Remember to immerse yourself in the things that bring you joy, and inner peace. If your situation indicates health issues, this is a card that indicates a replenishing and healing of the physical body as well.\
",
18:"The Moon<p>\
The Moon is the nineteenth card in the Major Arcana, and is given the number 18 to indicate the conscious mind represented by the Magician (1) assimilating the wild rage of the lion with the spirituality of the maiden in Strength (8). (Also, in planetary magick, 9 is the number of the Moon, and 1 plus 8 equals 9.) A lobster-like creature rises from the water, as it has been theorized that humankind originally did. It begins to travel a path toward the Moon. The path is flanked by a dog and a wolf—one tame, one wild—two sides of the same coin. In the distance, the path winds between two pillars, obviously manmade. The journey could represent the development of humankind, with the goal being a return to the psychic energy we were created in, embodied here by the Moon. The Moon controls the tide, and also brings out the wilder side in people. It is historically linked with magic and portents, and its mysteries are eternal. It is also associated with illusions, and what is seen by its light is not necessarily real...\
When the Moon appears in your future, it indicates a time to come when things will not be as they seem. Deception of one’s self, or from another, is strongly indicated. You should us extreme caution when dealing with others. New information will come to you, possibly in dreams or through a vision. In any case, when the truth is exposed, it will need to be dealt with. Accepting the darker, wilder side will bring peace; denial can only bring chaos.\
",
19:"The Sun<p>\
The Sun is the twentieth card in the Major Arcana, and is given the number 19 to indicate the conscious mind represented by the Magician (1) reaching the self-actualized state of the Hermit (9). A golden-haired child rides bareback on a pure white horse, carrying a red flag. This child is reminiscent of the one who held the flowers up to death, now riding the same white horse of purity, but carrying a red flag instead of a black one, indicating vitality and passion. The child is reborn. The only item the child wears is a headdress, topped with a feather, which symbolizes truth. The Egyptian goddess Ma’at wears a feather on her head—a feather that is used to weigh the souls of the recently deceased to determine if they are worthy to join the Gods in the afterlife. The sunflowers all turn toward the child, denoting that this is truly a child of the Light, as sunflowers are known to turn toward the sun for sustenance. The sun itself shines down on the scene in all its splendor, giving warmth and light to all living things.\
The Sun in your future signals a personal rebirth. You will feel that light is finally returning to your life. Obstacles will be surmounted, filling you with a new sense of happiness. This card can indicate that some money problems will be solved. The wealth you will experience may also be attributed to a new relationship, a new career, or a new feeling of health after a bout with illness. If you are currently in a committed relationship, The Sun can indicate a proposal of marriage on the horizon. Overall, this card is like the welcome calm after a storm, and indicates a time of pure joy that is yet to come.\
",
20:"Judgement<p>\
Judgement is the twenty-first card in the Major Arcana, and is given the number 20 to indicate the subconscious, intuitive mind of the High Priestess (2) experiencing the vast, pure potential of the Fool (0). The souls of the dead rise up from the darkness of the grave to heed the call of Judgement. Gabriel, the archangel, blows the horn to signal the time when each person will have to answer for his or her deeds. Gabriel’s hair appears like flames, calling to mind images of the phoenix, the mythological creature that rises from its own ashes, reborn. Judgement is the awakening of the souls, and the time to return to the realms of spirit, leaving the physical world behind. The coffins appear to be floating in an ocean, and a strange blue aura covers everything beneath the angel’s horn. This ocean is the subconscious that is only experienced in waves while the spirit resides in the body. When the soul is called forth, it is fully immersed in the collective unconscious.\
Judgement in your future denotes a milestone in the development of your soul. You will walk through fire, and come out of it transformed, and renewed. It indicates a time in the future when you will be liberated from your past, and marks your awareness of this freedom. This will be a good time to make the change complete. You may want to honor and mark your change in some way, major or minor. Acknowledging when you reach this point and releasing any leftover negative reminders from the “old” you will be the final steps in the process.\
",
21:"The World<p>\
The World is the twenty-second card in the Major Arcana, and is given the number 21 to indicate the subconscious mind of the High Priestess (2) uniting completely with the conscious mind of the Magician (1). A figure dances in the center of a giant victory wreath. The creatures that symbolize the four elements have materialized, taking on more realistic forms. The dancer is widely considered a hermaphrodite, symbolizing the unity of the masculine and feminine aspects to form a complete whole. The wreath is adorned with two red sashes, each one forming the sign of infinity. These symbolize the eternal cycle of life, death, and rebirth. The dancer passes through the wreath, entering a new phase of development, holding two wands. These wands channel the energy outward and inward, in an endless flow. The Wheel has come full circle, and the Dance of Life begins again, coiling ever upward toward divinity.\
The World in your future indicates unlimited potential put into experienced hands: the opportunity of a lifetime. Its image literally states “the sky’s the limit”. If you have been waiting for your chance, this will be IT. You will have the tools to accomplish your goal, and the door will be open. The World is a card of action. Of all the Major Arcana, only the first (The Fool) and the last (The World) show movement. While The Fool is like the dawn of creation and its promise, the World is like the hallmark of self-actualization. The benefits in store for you are truly as limitless as the cosmos this card represents.\
",
22:"Ace of Wands<p>\
All that is best in the suit of Wands is embodied in the Ace: the power of Will, desire, sexuality, and vitality will be abundant in the future. Just as the leaves burst forth with such force that they are seen falling from the Wand, your energy will bring forth many fertile beginnings. This card symbolizes the healthy, positive outlook that should be held. Great things are indicated.\
",
23:"Two of Wands<p>\
The Two of Wands represents opportunity, especially in business. You may soon be laying the foundation for a new venture. You have already achieved some success, indicated by the wand fastened securely to the castle wall. Also note the lilies of purity balanced by the red roses of desire. This shows the balance with which you will approach your goal. The wand in one hand represents your undertaking and the globe in the other suggests the tremendous potential for success. The character in the image, looking out to sea, suggests trade and could indicate strong partnerships and alliances. You will soon be in the early stages of a prosperous enterprise.\
",
24:"Three of Wands<p>\
The person depicted in the Three of Wands will send his ships out, staying behind to “hold the fort”. This card can indicate the desire to maintain existing relationships while testing the waters of new ones. In business terms, this is job hunting while you are still gainfully employed; in matters of love, this can indicate the desire to have an affair. Ponder the needs you would fill with whatever you seek.\
",
25:"Four of Wands<p>\
The successful completion of projects is indicated by the Four of Wands. The garland hanging from the four wands suggests that your goals will soon be achieved. The castle represents the solidity and splendor of what you will create. The characters in the image hold the harvest of their efforts high in the air in celebration of their success. You should soon enjoy the well-earned fruits of completion.\
",
26:"Five of Wands<p>\
Healthy competition is indicated by the Five of Wands. Notice that nobody in the picture is causing harm to another. They are all simply vying for position. This card indicates that you will be in the position for success in business or in the workplace, but that competition could slow you down. Don't spend too much time on the weaknesses of others, rather than amplifying your own strengths and good qualities. Competition can often be good and force you to perform at your best level, but don't let it become an obsession for its own sake.\
",
27:"Six of Wands<p>\
Some congratulations will be in order! You will be crowned with the wreath of victory on some level, and while the end will be a while in coming, you will still ride high on your achievement. Your belief in yourself will be renewed, and others will be inspired by your success. Note how the crowd in the card seems to line the street as the man rides through them on his horse: those around you will support your efforts, and celebrate your triumph with you. Remember to take a bow!\
",
28:"Seven of Wands<p>\
The Seven of Wands is a card of defense and confrontation. You will soon be forced to face a conflict head on. You will be cornered and will have no choice but to confront the source of the turmoil. While you are successful and respected, there are those around you who would seek to knock you off your throne of position. Your only choices will be to forfeit what you've worked for or to fight. Wands represent passion and fire and these are what you feel for your position and what you've accomplished. Use your vantage point at the top of the mountain to strategically plot your next move. This will not be a time for compromise. You must adhere to your deeply held beliefs if you want to succeed in the battle.\
",
29:"Eight of Wands<p>\
Swiftness, closure, and the end of opposition are symbolized by the Eight of Wands. The wands pointing downward, toward the lush green earth, shows that you will soon reach your destination successfully. Sometimes this card can be quite literal, indicating that you will soon take and complete a trip by air. However, most often it signifies successful and speedy completion of a goal.\
",
30:"Nine of Wands<p>\
The Nine of Wands indicates a pause, a time to “wait and see.” You have seen many battles relating to your situation, and you have fought hard. Like the man in the card whose head is bandaged but unbowed, your Will remained intact. These conflicts have strengthened you, but they have hardened you, making you better able to weather life's struggles, but at what price? Make a note of your defenses and when they were triggered...they may have made you seem unapproachable. Someone was trying to earn your trust, which has been hard won at best. You may have seen trouble where there wasn't any.\
",
31:"Ten of Wands<p>\
Depicting a person over-burdened by a heavy load, the Ten of Wands indicates that you will have a lot of irons in the fire—be careful not to get burned! You may overextend yourself. Though you typically enjoy being busy, there will come a time to delegate if possible to reduce your stress and give you more time to enjoy a taste of freedom. Choose your challenges wisely, and you will be able to give more of yourself to them.\
",
32:"Page of Wands<p>\
Frequently, this card refers to you, or someone who will strongly influence your life in the situation, but does not have to be male. The Page of Wands indicates the beginning of a project, relationship, or path. It can also indicate that you will lack confidence in the new situation. This may be expressed through indecision, confusion, or even “cold feet”. Examine your reasons for resisting a commitment to a new situation you will encounter, and confront the issues raised by reflecting on the feelings, hopes, and fears it will evoke.\
",
33:"Knight of Wands<p>\
Frequently, this card refers to you, or someone who will strongly influence your life in the situation, but does not have to be male. When you see the expression on his face, you know the Knight of Wands is an aggressive person, full of eagerness. He bears the totem of the element of Fire, the salamander, on his tunic. Even his horse is rearing up, raring to go. The energy of this card is that of action and movement. You can harness this energy, but remember to “ground” yourself. You must think clearly to accomplish your goals. Don't get caught up in the situation: take time to think things through before you act.\
",
34:"Queen of Wands<p>\
The receptive aspect of Fire, the Queen refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be female. In the card, the black cat at the Queen's feet can signify a guardian. Someone will be watching out for you, or one close to you. Her throne is adorned with Lions, totems of Fire, symbols of royalty, and traditionally seen as fierce guardians. The Queen herself is full of passion. Her parted legs signify her intense desires and strong sexual energy. If this energy is not found in your life, you will feel stagnant, bored, or hopeless. If it is pursued, you may experience a time of great pleasure and joy. Just as the sunflower depicted on the card always turns toward the light, the Queen of Wands seeks the positive. She shows a real lust for life. Will you?\
",
35:"King of Wands<p>\
The King refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be male. The King's throne bears the totems of the element of Fire: the salamander and the lion. His command of this element, which signifies the Will, is further supported visually by the tiny lizard at his feet. He appears as a strong-minded individual, sometimes manipulating others through his Will. This forthright person will be honest, fiery, and optimistic, and may feel like a natural leader. This energy should be channelled away from others and into the pursuit of long term goals, especially career-oriented ones.\
",
36:"Ace of Swords<p>\
In the Ace of Swords, the crowned sword of intellect is held over the mountains, literally denoting the triumph of mind over matter. Truth and honesty will prevail, symbolized by the palm of victory, and peace will be found, symbolized by the olive branch. Violent acts of force will not be necessary to achieve your goals. Your determination and strength of Will shall defeat the obstacles in your path.\
",
37:"Two of Swords<p>\
The Two of Swords symbolizes a choice you will face. The decision is put off, and the seeker is stuck, unable to face the truth. The blindfold she wears willingly shows her inability to open her eyes to reality. She has chosen to turn away from her intuition and emotions, symbolized by the ocean. She is a passive participant, crossing her arms over her chest to protect her heart. Putting this decision off may buy you time to gain control over your emotions, but the decision will inevitably have to be made, and if you wait, it may be made for you.\
",
38:"Three of Swords<p>\
One of the most disquieting cards of the Tarot is the Three of Swords. The images show three swords penetrating the heart, which implies that you may soon go through a state of intense sorrow. This card shows separation, divorce, and perhaps even the harmful intrusion of a third party, as in an extramarital affair. The falling rain seems to enhance the dismal nature of this card, but fear not: from the fall of rain comes growth. You will become stronger from this experience, and your own inner love will shine through.\
",
39:"Four of Swords<p>\
The Four of Swords represents an inner retreat that you will require. Your present situation is very difficult and you may be in the midst of much turmoil. A temporary truce is in order, and you will soon seek recuperation within. The swords on the wall symbolize your previous battles, and the sword at your side represents your current conflict. Upon completion of your withdrawal from this stressful situation, you will take up the sword again. The battle isn’t over, but when you return to it, you’ll be invigorated and able to formulate a mature, effective response. When combined with the Eight of Wands or the Six of Swords, this card can also mean that some kind of an actual trip will take place, one intended to bring you peace of mind.\
",
40:"Five of Swords<p>\
The Five of Swords indicates defeat. You may soon lose a battle (most likely a mental one), and find yourself in retreat, seeking to calm the choppy waters of your emotions. The character collecting the swords suggests that a score-keeper, motivated by revenge and vindication, will be at the heart of your troubles. This card can also be a warning to you to avoid your own lusts for revenge, showing that only hurt and pain will be the result. Remember to take time to heal your wounds. Concede your defeat when it arrives, and find new things to focus on.\
",
41:"Six of Swords<p>\
The Six of Swords represents a retreat that you will take. You will be dealing with heavy stress, signified by the choppy water behind the boat. This card can also indicate that you will feel “haunted” by someone or something, and you will seek closure. You will leave this behind, setting forth for the calmness of still waters. You will learn to balance your mental state, evidenced by the swords that do not fall though the boat is in motion. You will also be the protector in the situation. Your loved ones will rely on you to carry them away from troubled waters. You won’t let them down.\
",
42:"Seven of Swords<p>\
The aggressor in the Seven of Swords slyly makes off with many of his enemy’s weapons, taking his opposition down a peg in an underhanded way. He cannot defeat the competition completely this way: some swords remain, evidence that the war is not over yet. He acts alone, indicating that the future of your situation is a somewhat clandestine one. Don’t get too wrapped up in mental games, one-upmanship, and petty battles that will not solve anything. In the weeks ahead, you should take the high road.\
",
43:"Eight of Swords<p>\
Oppression is symbolized by the Eight of Swords. You will feel trapped and alone, unable to see your way through to a solution. The castle in the background suggests the authority figure that you may feel is keeping you down. The swords are the opposition that could keep you where you are. Look closer. Will you be helping to keep yourself there? Notice that the woman in the picture does not have her feet tied, nor are the swords blocking her way. You will be free to go. The oppressor in your life may actually be real, but you must not give away your power. When you feel that it’s time to move on, trust your inner voice.\
",
44:"Nine of Swords<p>\
The depth of mental anguish felt by the person in the Nine of Swords is beyond description. The carving on the bed shows the violence that arises, and suggests that someone you love may be involved in the battle. The swords on the wall indicate that you will not be struck directly at this time. Sleepless nights, anxiety dreams, and worry will plague you: note that the person sits up, head in hands, crying alone in bed. This body language epitomizes guilt, depression, and despair. There will be a need for comfort, emotional shelter, forgiveness, and healing.\
",
45:"Ten of Swords<p>\
The swords stuck in the person’s back symbolize failed plans, loss, and defeat, but the sheer number of swords, ten, can indicate over-dramatization of the situation. It probably will not be as bad as it will seem to the one who will be in it. The water is calm, the sky on the horizon is light, and it is the darkest hour that will be passing. Soon after, the dawn will come, and a new beginning with it, so remember not to lose hope.\
",
46:"Page of Swords<p>\
Frequently, the Page of Swords refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be male. He will seek higher ground, using his standpoint to master difficulties. He watches for trouble over his shoulder. In the card, the wind blows the trees and his hair, symbolizing changing circumstances, unpredictable behaviors, and wavering opinions that will compound the situation. Flexibility and adaptability will be key.\
",
47:"Knight of Swords<p>\
Frequently, this card refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be male. The Knight of Swords will come to the fight primed for battle, his sword waving a challenge to all comers. He will lead with his sword, then his head, then his heart. The mind of the person in question, like the Knight’s, is swift and will require constant stimulation. The butterfly on his horse is a symbol of his emergence from a chrysalis: he will rapidly transform into the blazing Knight depicted on the card. He will make a powerful impression, appearing suddenly, aggressively...but will his enthusiasm carry him through to the end, and will his high energy last?\
",
48:"Queen of Swords<p>\
The Queen refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be female. She holds the sword of truth upright. She faces reality, and while she endures many sorrows, she has learns to accept the truth. The butterfly on her crown is a symbol of her emergence from a chrysalis: she will transform into the self-assured Queen depicted on the card. The tassel dangling from her wrist is like a freshly severed rope, which signifies her release from the bonds of confusion, doubt, and illusion. You will use her as your example: see clearly, and think freely.\
",
49:"King of Swords<p>\
The King refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be male. He will be an authority figure who wears the yellow crown of mental energy. The butterfly on his throne is a symbol of his emergence from a chrysalis: he will transform into the confident King depicted on the card. He has fought many psychological battles, and has gained wisdom, hence his purple mantle. He will listen carefully to all sides, basing his judgement on his own experiences, trying to make the fairest decision. The birds flying over him, symbols of Air, fly above it all. Their vantage point offers them an impartial view, just like that of the King. He will sometimes appear unapproachable, unfeeling, and cold because of his remote countenance. Remember to apply his view to your situation.\
",
50:"Ace of Cups<p>\
The Ace of Cups in your future indicates that you will soon be experiencing a wellspring of emotions, especially love. You will soon find a new love interest, or discover renewed feelings in a relationship you already have. The dove, representative of spiritual love, symbolizes the depth to which this emotional renewal will touch you. It will give you a new emotional perspective. The water flowing from the cup suggests that your emotional being (represented by the water below) will be recharged from this outpouring.\
",
51:"Two of Cups<p>\
Love and deep friendship are suggested by the Two of Cups. You may soon be entering into a fulfilling love relationship. This union will be based on passion and strength, symbolized by the lion, and a healthy attitude, suggested by the Caduceus, or wand of medicine. The man and woman facing each other, staring into one another’s eyes, suggest the deeper sense of understanding that exists between them. You will probably feel an understanding with this person that you have felt with few others. You may even be thinking of or discussing marriage.\
",
52:"Three of Cups<p>\
The Three of Cups indicates the celebration of friendship, and the joy of being together. You will soon be enjoying time with close friends and remembering the good times that you have shared. Great achievements will be toasted among you, suggested by the bountiful harvest at the feet of the women celebrating. This will be a time of appreciation of the deeper sense of understanding that you share with your closest friends. It is said that we find few true friends in our lifetime. Treasure yours always.\
",
53:"Four of Cups<p>\
The Four of Cups indicates a strong sense of emotional retreat and discontent that you will soon be experiencing. The man sitting against the tree seems to be closed off to new ideas. You may have a tendency to focus on the boredom you feel with what you already have, suggested by the three cups at the man’s feet. A new opportunity will be offered you and you may turn it down, deciding instead to close yourself off. Perhaps you will feel you need this retreat, and will need to evaluate what’s important to you, but spending too long in this mode could prevent you from moving forward.\
",
54:"Five of Cups<p>\
The Five of Cups suggests that you will soon be upset over a loss or disappointment. The three cups spilled at the man’s feet in the picture indicates the loss you may experience. You may not be aware of the strong support system that remains, indicated by the two cups still standing. Your friends and loved ones will offer their support but, for a while, you may focus too much on the disappointments. The river in the image suggests the troubled emotions that may soon make you feel lost and distant; you may cut yourself off from the joy and love associated with home. Remember to notice the bridge that isn’t far from view. It can lead you home again, into the arms of your loved ones.\
",
55:"Six of Cups<p>\
Childhood memories, family gatherings, and friends from the past are all suggested by the Six of Cups. You may soon encounter a friend or lover from your past that you haven’t seen in many years. The child bearing the flowering cup indicates the positive nature of this meeting. The pleasant home in the background is also a strong indicator of family and home. You may soon be spending more time with family and old friends. Celebrate your past. It is the foundation for your dreams and goals in the future.\
",
56:"Seven of Cups<p>\
Flights of fancy and daydreaming are indicated by the Seven of Cups. In the picture we see the many visions of happiness that the character sees in the cups, but they are all unrealistic goals at this time: a castle in the clouds, jewels, dragons, and holy figures, among others. You may soon be experiencing a preoccupation with visions of fantastic goals as a means of escaping an emotional reality you aren’t able to confront. Don’t let these ideas cloud your vision: there are real and tangible sources of happiness in your life and those are the things you should treasure. Remember to open up to the love around you.\
",
57:"Eight of Cups<p>\
The Eight of Cups suggests that you are about to begin an important journey of self-exploration. The cups the character in the picture is leaving behind seem organized and stable, though there is a noticeable gap in them. This shows that you will have a relatively stable situation that you will be leaving behind, but that you will be feeling that there is something more, something your soul is seeking. The moon is shown eclipsing the sun, which shows how your search for deeper meaning will block out the importance of ordinary daily life. You must climb the mountain to find your spiritual peak. It is said that the journey of a thousand miles begins with one step.\
",
58:"Nine of Cups<p>\
Enjoying the fulfillment of desire is indicated by the Nine of Cups. You may soon reach a place in your life where you are comfortable and happy, and are able to enjoy the many rewards of your past actions. Contentment and luxury are suggested by the imagery of the man, sitting comfortably, enjoying the nine cups arranged on the banquet table. Life is your banquet, and you’ve earned the right to enjoy it. In old tradition, the Nine of Cups is the \"Wish Card\" and was always thought to mean the fulfillment of one’s innermost desires.\
",
59:"Ten of Cups<p>\
The Ten of Cups suggests the success of family and emotional fulfillment. The rainbow is the promise of stability and protection, and in the Bible, the rainbow was used as God’s promise that he would never again send a flood of destruction to the earth. You may soon go through a process that helps you to realize how strong your family is, and what they have done to help create who you are and give you strength. Your current family, if you have one, will be growing closer, perhaps after a very trying time. This card can also signify the start of a new family, like a young tree sending its first roots into the ground.\
",
60:"Page of Cups<p>\
The Page of Cups is a card of creative imagination, deep feelings, and psychic aptitude. The young man in the picture stands in front of the great sea of emotions in the background. The fish emerging from the cup represents the range of the Page’s great imagination. The Pages are students, and so in the suit of Cups the lessons learned are the exploration of emotion, imagination, and perhaps even psychic ability. This card can represent a state of being you will soon be experiencing, or possibly a younger person in your life with these qualities who may soon become a source of emotional strength for you.\
",
61:"Knight of Cups<p>\
The Knight of Cups, dressed in blue to denote his sensitivity and emotional nature, signifies a dreamy, caring, loving individual in your future. This Knight will pursue his thoughts and fantasies, and intuitively attune to the needs of others. He may signify a lover who will not wish to commit, who is attractive, but passive. He will do what he believes in, and will be considered a charmer...someone you will meet, or could this be you?\
",
62:"Queen of Cups<p>\
The Queen of Cups knows what she wants, and takes the steps necessary to get it. She symbolizes the strength of the abilities of the imagination and the psychic self. Seated at the edge of the ocean, she dips into these powers. As water takes the shape of its container, the Queen assumes the moods of others. This is what you will need to do, or it may describe the actions that will be taken by a person important to your current situation.\
",
63:"King of Cups<p>\
The King of Cups directs his creative powers to achieve success. He practices self discipline, sometimes even at the expense of his dreams, to rise to power. The water seen rolling in waves denotes his emotional powers, as he is a caregiver, capable of manifesting harmonious situations and feelings. You, or one close to you, will channel creative energy into something to benefit more than yourself, or him/herself.\
",
64:"Ace of Pentacles<p>\
The hand in the Ace of Pentacles bestows its blessings in a garden full of a variety of delights. Earth’s bounty is physical and comes in the form of tangible pleasures. Patience brings prosperity, and the one who has worked hard on this garden now takes pride in its beauty and abundance...good tending yields good results. The floral gate in the background, reminiscent of the ring surrounding the self-actualized person on the World card, can indicate a door of opportunity for new business, property, or other practical assets that will open up for you.\
",
65:"Two of Pentacles<p>\
Juggling two situations at once with ease, the person in the Two of Pentacles personifies the choices we make every day. Like the ships on the rough seas behind him, he has experienced ups and downs in the endless tide of life, symbolized by the infinity sign in the pattern surrounding the pentacles. Every new choice made brings change, a new opportunity, and a fresh start. It is said that the only thing constant is change. You will triumph in this situation if you remain flexible and adapt, rather than resist.\
",
66:"Three of Pentacles<p>\
The Three of Pentacles is a card of Mastery. The craftsman in the image is proud of his work and is happy to display it to others. You will soon finish a large project that you’ve been working on for some time, and will begin to enjoy the fruits of your labor. Your competence and desire for perfection will show through in your excellent work. If combined with the Ace of Pentacles, this card may indicate earning an academic degree. Either way, you will deserve the praise you’ll receive for a job well done.\
",
67:"Four of Pentacles<p>\
The Four of Pentacles indicates that you will achieve stability through reliance on material gain...but in the process, you may block yourself from the world around you, symbolized by the character in the image who covers his head, heart, and feet with his wealth, protecting himself from interference from the outside world. What are you afraid of losing, so much that you will hoard everything you can? You will prove that you are adept at saving money, and you deserve the hard earned financial success you’ll win, but remember to take time out to enjoy some of the bounty of your success.\
",
68:"Five of Pentacles<p>\
The two unfortunate travelers experience severe hardships: loss of property, income, and health are all indicated in the bleak picture that is the Five of Pentacles. The church in the background is not a refuge for them: either they refuse its charity, do not recognize the opportunity it represents, or find no nourishment there. While a pessimist might focus on what they lack, an optimist would point out that they survive these hard times together, supporting each other. In this case, attitude will mean everything. Perseverance furthers—your strength will be found in those who love you.\
",
69:"Six of Pentacles<p>\
A quick glance at the Six of Pentacles shows a generous person giving to those less fortunate. The fact that the giver is standing while the others kneel reveals the deeper meaning. The scales symbolize the balance of power, which benefits both the giver and the receiver to varying degrees in this situation. The person or entity giving bases this generosity on the power it has over those who accept the charity or aid, and this may be mental, emotional, or sexual favors, not necessarily material ones. The person giving could actually be a job, and may be dominating an entire group of people who remain in the situation because they do not want to risk a change. You may find that you will get what you need, but not what you want, and you will have to decide if your desires are strong enough to draw you out of your comfort zone.\
",
70:"Seven of Pentacles<p>\
The Seven of Pentacles represents a sense of dissatisfaction that you may feel with the results of a project you will complete, either in the workplace or in your personal life. What you plant will bear fruit, but not quite to your satisfaction. Despite the less than satisfactory results, you’ll be glad that the project is over. You will be grateful that you’ll have time to relax, but you may feel that you could have done more. There will be much to be thankful for. You’ll have to create something that will have a life of its own, and it will continue to grow. This card can often be a warning against perfectionism, and a sign that you must sometimes step back and let go.\
",
71:"Eight of Pentacles<p>\
Skill and talent combine to form the energy of the Eight of Pentacles. The gentleman works diligently on his project, taking great care to produce quality, not quantity. His attention to detail and genuine love of his work will make him a master someday, but that is not his top priority. He loves his work, and betters himself as a person through it. The road from his workshop to the city in the distance shows his other motivation: doing well for the benefit of the community, not just himself. Be sure to examine what you put your energy into, and realize that you derive more pleasure from work that benefits others as well as yourself.\
",
72:"Nine of Pentacles<p>\
The person in the Nine of Pentacles has made her own way, and enjoys freedom within the boundaries she has created for herself. The wall of Pentacles she touches has been created and nurtured by her. She is alone but for her falcon, symbol of the intellect, which she has trained. The bird, like her, enjoys a modicum of freedom within the boundaries of its responsibilities. This person will be self-sufficient, and cherish her private time, her “space”. She will sacrifice adventure and reckless abandon to achieve her goals, and know she is making the right choice.\
",
73:"Ten of Pentacles<p>\
Overall, the Ten of Pentacles is a card of a good home life, security, prosperity, and happiness...on the surface. Looking closer, the family appears not to notice how lucky they are, which is the deeper message of the card. The man and woman do not walk together; rather, they pass each other briefly as they go through their mundane motions. The people in the situation will take what they have, and each other, for granted. They will be so wrapped up in their daily routines that they will not take the time to acknowledge the magic and blessings around them, symbolized by the ten pentacles surrounding their home. The ten pentacles also have a deeper meaning, echoing the ten Sephiroth of the Tree of Life. Remember to look past the trappings of the material world, and seek the blessings of the soul.\
",
74:"Page of Pentacles<p>\
Frequently, the Page refers to you, or someone of either sex who will strongly influence your life in the situation, and tends to be young or have a youthful semblance. In this card, the Page’s garments of brown and green demonstrate his connection to the earth. He gazes at his pentacle with pride and reverence; he does not take what he has for granted because he has worked so hard to earn it, and he knows he deserves what he has. He is the student, mezmerized by each mystery his studies reveal. The pay-off will matter very little to this person: he will do what he loves to do. His success will stem from his passion for his chosen field.\
",
75:"Knight of Pentacles<p>\
Frequently, the Knight refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be male. The way the Knight of Pentacles sits upon his horse, upright, and the way his steed appears to stand, steadfast, epitomizes the essence of this card, and the person in question. He stares out beyond his pentacle, which can indicate that he will be so busy working that he will neglect or forget what he works for. The Knight of Pentacles signifies a person who will give his greatest effort in all he does, but may sometimes be so driven and so determined that he may lose sight of what matters most to him.\
",
76:"Queen of Pentacles<p>\
The receptive aspect of Earth, the Queen refers to you, or someone who will strongly influence your life in the situation in question, but does not have to be female. Her outdoor throne, surrounded by Earth’s prosperity and abundance, denotes that she takes charge of money matters in a cautious and practical manner, and that she is successful in her business dealings. Her productivity and creativity are symbolized by the appearance of several blooming plants, and the hare, traditionally associated with fertility. This person will value her self-sufficient independence, and work hard to maintain her “creature comforts”. The Queen reminds us to return to our connection with the earth, and to tap into the creative force in everything.\
",
77:"King of Pentacles<p>\
The King refers to you, or someone who strongly influences your life in the situation in question, but does not have to be male. The King’s closeness with nature is apparent in the symbols of Earth’s plenty, which adorn him. The flowers and grapes symbolize the beauty and bounty he enjoys, seated in his garden, reflecting on all his hard work. He gazes fondly at his pentacle: he is at ease with his status and the responsibility it bestows upon him. A successful professional, this person will be practical, and sometimes possessive. He will be content with his accomplishments. In this case, it may be his career, or his home that he will be proud of.\
"
}
